name: codesign
description: A standalone app to codesign Mac engine binaries.
version: 1.0.0
homepage: https://github.com/flutter/cocoon

environment:
  sdk: '>=2.18.0-170.0.dev <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
