name: codesign
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-80.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  archive: ^3.3.0
  args: ^2.3.1
  platform: ^3.1.0
  process: ^4.2.4
  file: ^6.1.2 
  crypto: ^3.0.1
  meta: ^1.7.0
  fake_async: ^1.3.0
